/**
 * Afiche database schema.
 *
 * Five tables: cinemas, films, screenings, providers, scrape_runs.
 *
 * Design notes:
 *   - All timestamps stored as UTC Unix integers. Rendering code converts to
 *     America/Argentina/Buenos_Aires timezone.
 *   - films.scraped_title preserves the raw title as first seen by a scraper —
 *     useful for debugging fuzzy-match quality against TMDB.
 *   - films.match_source tracks the outcome of TMDB enrichment. Possible values:
 *       'auto'            — fuzzy match succeeded, confidence >= threshold
 *       'override'        — matched via tmdb-overrides.json
 *       'manual'          — operator set tmdb_id directly in Drizzle Studio;
 *                           the next enrichment pass fetches details for that
 *                           id and fills in poster/director/year/synopsis. The
 *                           'manual' sentinel locks the row from re-search.
 *       'none'            — never attempted (new row, or explicitly reset)
 *       'none-attempted'  — attempted and failed (no candidates / low confidence);
 *                           the scraper will NOT re-query TMDB for this row on
 *                           subsequent runs UNLESS tmdb_id is also set (in which
 *                           case the manual-patch path takes over). Transient
 *                           errors (network, TMDB 5xx, missing token) leave the
 *                           row at 'none' so it retries.
 *                           To force a re-attempt after improving the matcher:
 *                             UPDATE films SET match_source='none'
 *                             WHERE match_source='none-attempted';
 *   - providers table is "latest state" observability: one row per cinema,
 *     holds last-run / last-success / last-error / current screening_count.
 *   - scrape_runs table is "history" observability: one row per cinema per run,
 *     never overwritten. Use for trend analysis, miss-rate over time, debugging
 *     ephemeral Vercel cron output after the fact. Warnings from each run are
 *     captured as a JSON array so individual TMDB misses stay searchable.
 */

import {
  sqliteTable,
  text,
  integer,
  real,
  uniqueIndex,
  index,
} from 'drizzle-orm/sqlite-core';

// ---------------------------------------------------------------------------
// cinemas — the venues we scrape
// ---------------------------------------------------------------------------
export const cinemas = sqliteTable('cinemas', {
  id: text('id').primaryKey(), // slug: 'malba', 'lugones', 'cinepolis-recoleta'
  name: text('name').notNull(), // 'MALBA'
  neighborhood: text('neighborhood'), // 'Palermo'
  type: text('type', { enum: ['indie', 'chain'] }).notNull(), // drives UX tier
  address: text('address'),
  ticketingBaseUrl: text('ticketing_base_url'),
  createdAt: integer('created_at', { mode: 'timestamp' })
    .notNull()
    .$defaultFn(() => new Date()),
});

// ---------------------------------------------------------------------------
// films — canonical film records, enriched by TMDB at ingest (best-effort)
// ---------------------------------------------------------------------------
export const films = sqliteTable(
  'films',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    // Title used for display. Populated from override > TMDB canonical > scraped.
    title: text('title').notNull(),
    // URL slug for /pelicula/<slug>. Deterministic from title + year (or id).
    // Generated by `buildFilmSlug()` in src/lib/slug.ts at insert time via
    // `upsertFilm()` which guarantees non-null. On UNIQUE collision (rare —
    // re-releases, festival cuts), upsertFilm applies a `-<films.id>`
    // tiebreaker.
    //
    // The slug is stable across the project's lifetime; if `title` later
    // changes via TMDB match, the slug does NOT update — URLs are the
    // contract. See design doc at
    // ~/.gstack/projects/kino/benjamin.delasoie-main-design-20260425-200910.md
    // for the slug stability rationale.
    //
    // Column is nullable at the DB level only because SQLite/libSQL doesn't
    // support `ALTER COLUMN SET NOT NULL` directly without a table rebuild.
    // Application code (upsertFilm + downstream) treats it as non-null.
    // A Phase 1.5 follow-up migration will tighten to NOT NULL once the
    // backfill is verified safe across all environments.
    slug: text('slug'),
    // Original-language title from TMDB (e.g. "Сталкер" for Stalker). May be null.
    titleOriginal: text('title_original'),
    // Raw title as first seen by a scraper — preserved for dedup / match audits.
    scrapedTitle: text('scraped_title').notNull(),
    director: text('director'),
    year: integer('year'),
    // The year as the SCRAPER first saw it on the source page. Immutable
    // after first insert — only `year` evolves (e.g., TMDB resolves a
    // year-less row to 2024). The (scraped_title, scraped_year) pair is
    // the upsert key; (scraped_title, year) is NOT, because `year` is
    // mutable and re-scrapes that emit year=null after enrichment filled
    // year=YYYY would otherwise miss the existing row and create an
    // unenriched duplicate. See the mutable-key upsert bug investigation
    // (memory: project_afiche_mutable_key_upsert_bug.md). Nullable
    // because some providers can't determine year (Lugones cycle pages
    // with truncated metadata, MALBA single-event pages, etc.).
    scrapedYear: integer('scraped_year'),
    country: text('country'),
    runtimeMin: integer('runtime_min'),
    synopsisEs: text('synopsis_es'),
    // Top-billed cast from TMDB credits. JSON array of { name, character }
    // sorted by TMDB's `order` (billing position, 0 = top). Capped at 8
    // entries — anything beyond top 8 is below-the-fold for the editorial
    // detail page and bloats row size for filtering. Null when the film
    // has no TMDB match yet, or when TMDB's credits response was empty.
    cast: text('cast', { mode: 'json' }).$type<CastMember[] | null>(),
    // TMDB genre IDs (the numeric ones from /genre/movie/list). JSON array.
    // We store IDs not localized names because TMDB occasionally tweaks
    // translations and IDs are stable; render layer resolves to display
    // strings via GENRE_LABELS_ES below. Same pattern as ScreeningTag +
    // TAG_LABELS_ES. Null until enriched, [] when TMDB returns no genres.
    genres: text('genres', { mode: 'json' }).$type<number[] | null>(),
    // TMDB's canonical ID. Populated when fuzzy match >= 0.8 OR via overrides.
    tmdbId: integer('tmdb_id'),
    // Cross-reference from TMDB response.
    imdbId: text('imdb_id'),
    // Own-CDN URL (Vercel Blob / R2), never a tmdb.org hotlink.
    posterUrl: text('poster_url'),
    // 16:9 cinematic still from TMDB (`backdrop_path`). Stored at w1280 — the
    // sweet spot for /pelicula's editorial-still slot at 2x DPR. Null when
    // the film has no TMDB match yet, or when TMDB has no backdrop on file
    // (common for shorts and long-tail festival titles). Render layer skips
    // the backdrop section entirely when null — the page degrades cleanly to
    // its no-image rhythm.
    backdropUrl: text('backdrop_url'),
    // Similarity score at match time; null if override or no match.
    matchConfidence: real('match_confidence'),
    // Provenance of the TMDB link. See schema-level doc comment above.
    matchSource: text('match_source', {
      enum: ['auto', 'override', 'manual', 'none', 'none-attempted'],
    })
      .notNull()
      .default('none'),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => [
    // Prevent duplicate film rows from the same scraped title + scraper-
    // emitted year. Keyed on `scraped_year` (not `year`) so the upsert key
    // stays stable even after enrichment fills in the `year` column —
    // otherwise a re-scrape can't find the existing row by its original
    // (scraped_title, year=null) key once year has been mutated, and ends
    // up inserting an unenriched duplicate.
    uniqueIndex('films_scraped_title_scraped_year_idx').on(t.scrapedTitle, t.scrapedYear),
    // Slug is the URL key for /pelicula/<slug> — must be unique.
    uniqueIndex('films_slug_idx').on(t.slug),
  ],
);

// ---------------------------------------------------------------------------
// providers — scraper health, observability, and per-provider state cache
// ---------------------------------------------------------------------------
//
// Two roles in one table:
//   1. Health/observability — last_run_at, last_success_at, last_error,
//      screening_count. Read by the dashboard.
//   2. Per-provider cache — last_image_sha256, last_image_parsed. Currently
//      used only by Lorca, which fetches a weekly poster image and pays
//      $0.005 + a drift dice roll per Anthropic call. Caching by image hash
//      means we only call vision when the poster changes (Thursday), not on
//      every daily scrape. Both columns are nullable; non-Lorca providers
//      simply never write to them.
//
export const providers = sqliteTable('providers', {
  id: text('id')
    .primaryKey()
    .references(() => cinemas.id), // same as cinemas.id
  lastRunAt: integer('last_run_at', { mode: 'timestamp' }),
  lastSuccessAt: integer('last_success_at', { mode: 'timestamp' }),
  lastError: text('last_error'),
  screeningCount: integer('screening_count').default(0),
  // 64-char hex digest used as the cache key for the last successfully-
  // parsed source artifact. For Lorca it's SHA-256 of
  // (imageBytes || ':' || VISION_MODEL || ':' || PROMPT_VERSION) so a
  // model upgrade or prompt revision automatically invalidates the cache
  // (otherwise a buggy parse could persist for the full week the poster
  // image stays unchanged). Column name kept as `last_image_sha256` for
  // migration stability — the value is still a SHA-256 digest, just of
  // composed inputs rather than image bytes alone. Other providers may
  // adopt the same pattern with their own composition.
  lastImageSha256: text('last_image_sha256'),
  // The parsed artifact corresponding to lastImageSha256, stored verbatim
  // as JSON so we can re-derive screenings without re-calling the model.
  // Format is provider-defined (Lorca stores ParsedCartelera). Only read
  // when lastImageSha256 matches the current fetch's hash.
  lastImageParsed: text('last_image_parsed', { mode: 'json' }),
});

// ---------------------------------------------------------------------------
// scrape_runs — history of every scraper invocation, one row per (cinema, run)
// ---------------------------------------------------------------------------
//
//     startRun() ──► inserts row with status='in-progress', started_at=now
//                    returns run_id
//     finishRun() ─► updates same row: status='success', finished_at,
//                    duration_ms, counts, warnings[]
//     failRun()  ──► updates same row: status='failure', error text
//
// Never overwritten. Retention is indefinite for now — at ~1 row per cinema
// per day per run frequency, even 5 years is a few thousand rows.
//
export const scrapeRuns = sqliteTable(
  'scrape_runs',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    cinemaId: text('cinema_id')
      .notNull()
      .references(() => cinemas.id, { onDelete: 'cascade' }),
    startedAt: integer('started_at', { mode: 'timestamp' }).notNull(),
    finishedAt: integer('finished_at', { mode: 'timestamp' }),
    status: text('status', { enum: ['in-progress', 'success', 'failure'] })
      .notNull()
      .default('in-progress'),
    durationMs: integer('duration_ms'),
    // Fetch-phase count — what the provider returned before dedup.
    screeningsScraped: integer('screenings_scraped'),
    // Ingest-phase count — what made it into the screenings table this run.
    screeningsInserted: integer('screenings_inserted'),
    filmsUpserted: integer('films_upserted'),
    filmsEnriched: integer('films_enriched'),
    enrichSkipped: integer('enrich_skipped'),
    // Fatal error string if status='failure'.
    error: text('error'),
    // Non-fatal warnings collected during the run (per-film TMDB errors,
    // parsing quirks, etc.). Stored as JSON array of strings.
    warnings: text('warnings', { mode: 'json' }).$type<string[]>().notNull().default([]),
  },
  (t) => [
    // "show me the last 20 runs for Lugones" — most common query.
    index('scrape_runs_cinema_started_idx').on(t.cinemaId, t.startedAt),
    // "show me all runs today across all cinemas".
    index('scrape_runs_started_idx').on(t.startedAt),
  ],
);

// ---------------------------------------------------------------------------
// screenings — the core table
// ---------------------------------------------------------------------------
export const screenings = sqliteTable(
  'screenings',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    filmId: integer('film_id')
      .notNull()
      .references(() => films.id, { onDelete: 'cascade' }),
    cinemaId: text('cinema_id')
      .notNull()
      .references(() => cinemas.id, { onDelete: 'cascade' }),
    // Always UTC. Rendering code converts to America/Argentina/Buenos_Aires.
    startsAtUtc: integer('starts_at_utc', { mode: 'timestamp' }).notNull(),
    // JSON array of ScreeningTag values.
    tags: text('tags', { mode: 'json' }).$type<ScreeningTag[]>().notNull().default([]),
    // Curatorial program / cycle the screening belongs to (e.g.,
    // "Retrospectiva David Lynch", "Olivera-Aries", "Hijo mayor"). Persisted
    // by indie scrapers (MALBA, Lugones, Lumiton-family, Cine York) when the
    // venue exposes a program/cycle context. Null for venues that don't
    // organize screenings into curated programs (Cosmos, etc.) AND for
    // single-event paths where the program would just echo the film title.
    //
    // Stored as denormalized text rather than a foreign key to a
    // `programs` table because /programa/<slug> destinations don't yet have
    // a killer feature (per /office-hours D2 2026-04-25). When they do
    // ship, a future migration extracts unique program names into a table.
    // See TODO #14 in TODOS.md.
    //
    // Display rule: render the pill on cards only when non-null. The
    // CHECK constraint enforces "null or non-empty" at the DB level so an
    // empty-string slip-through doesn't render an empty pill.
    programName: text('program_name'),
    // Back-link to the cinema's ticketing or programming page for this screening.
    sourceUrl: text('source_url'),
    scrapedAt: integer('scraped_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => [
    // Fast "next 7 days" query
    index('screenings_starts_idx').on(t.startsAtUtc),
    // Fast "by cinema" filter + stale-data check
    index('screenings_cinema_idx').on(t.cinemaId),
    // Prevent duplicate screenings from multiple scraper runs (same film, cinema, time)
    uniqueIndex('screenings_unique_idx').on(t.filmId, t.cinemaId, t.startsAtUtc),
  ],
);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ScreeningTag =
  | 'unique' // ÚNICA FUNCIÓN
  | 'restored' // COPIA RESTAURADA
  | 'retrospective' // RETROSPECTIVA
  | 'premiere' // ESTRENO
  | 'cycle' // CICLO
  | 'vos' // versión original subtitulada
  | 'dubbed'; // doblada

/**
 * Top-billed cast entry from TMDB credits. Stored as JSON in films.cast.
 * `character` is sometimes empty in TMDB's response (uncredited / unknown
 * roles); render layer should treat empty character as "no role label".
 */
export interface CastMember {
  name: string;
  character: string;
}

/**
 * TMDB movie genre IDs → es-AR display names. The full vocabulary from
 * TMDB's /genre/movie/list endpoint. IDs are stable; names follow TMDB's
 * es-AR localization (which can drift over time, hence the map lives in
 * code rather than the DB).
 *
 * Used by:
 *   - Render layer: resolves stored genre IDs to display labels
 *   - Future filter UI: enumerates the vocabulary as filter chips
 *
 * If TMDB ever adds a genre, add it here. Unknown IDs in DB rows render
 * as falsy via the lookup → caller can choose to skip or fall back.
 */
export const GENRE_LABELS_ES: Record<number, string> = {
  28: 'Acción',
  12: 'Aventura',
  16: 'Animación',
  35: 'Comedia',
  80: 'Crimen',
  99: 'Documental',
  18: 'Drama',
  10751: 'Familia',
  14: 'Fantasía',
  36: 'Historia',
  27: 'Terror',
  10402: 'Música',
  9648: 'Misterio',
  10749: 'Romance',
  878: 'Ciencia ficción',
  10770: 'Película de TV',
  53: 'Suspense',
  10752: 'Bélica',
  37: 'Western',
};

export const TAG_LABELS_ES: Record<ScreeningTag, string> = {
  unique: 'ÚNICA FUNCIÓN',
  restored: 'COPIA RESTAURADA',
  retrospective: 'RETROSPECTIVA',
  premiere: 'ESTRENO',
  cycle: 'CICLO',
  vos: 'VOS',
  dubbed: 'DOBLADA',
};

// Drizzle's auto-derived row types (use these in your code)
export type Cinema = typeof cinemas.$inferSelect;
export type CinemaInsert = typeof cinemas.$inferInsert;
export type Film = typeof films.$inferSelect;
export type FilmInsert = typeof films.$inferInsert;
export type Screening = typeof screenings.$inferSelect;
export type ScreeningInsert = typeof screenings.$inferInsert;
export type Provider = typeof providers.$inferSelect;
export type ProviderInsert = typeof providers.$inferInsert;
export type ScrapeRun = typeof scrapeRuns.$inferSelect;
export type ScrapeRunInsert = typeof scrapeRuns.$inferInsert;
